baseURL = "http://chenxiaoyu.org/"
languageCode = "zh-CN"
title = "smallfish's blog"
pygmentsuseclasses = true
publishDir = "docs"
theme= "hugo-theme-crisp"

[permalinks]
posts = "/:year/:month/:day/:filename/"

